#!/usr/bin/env bash
# This script configures the IP addresses for localhost and facebook.com

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify /etc/hosts file to set localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i 's/^127.0.0.1.*$/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/^.*facebook.com.*$/8.8.8.8 facebook.com/' /etc/hosts

